# Generated by Django 3.0.5 on 2020-06-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200526_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='catalog-image'),
        ),
    ]
