# Generated by Django 3.0.5 on 2020-06-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200609_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
    ]
