# Generated by Django 3.0.5 on 2020-06-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_author_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
