# Generated by Django 3.0.5 on 2020-06-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200609_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalog-image'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter agenre (e.g. Science Fiction)', max_length=200),
        ),
    ]
